/**
 * PORTFOLIO DATA — main content lives here
 */
const PORTFOLIO_DATA = {
  projects: [
    {
      id: 'capstone',
      title: 'Enterprise Network Capstone',
      category: 'academic',
      description: 'Built an enterprise network from scratch: Active Directory, SQL, email, and web servers, firewall hardening, CSET analysis, and penetration test prep.',
      tech: ['Windows Server', 'Linux', 'Kali', 'AD', 'SQL', 'Snort', 'Python'],
      url: null,
      live: false,
      featured: true,
    },
    {
      id: 'proxmox-lab',
      title: 'Proxmox VE Hypervisor Lab',
      category: 'security',
      description: 'Type-1 hypervisor on HP EliteDesk Mini (i5-8500T, 16GB RAM, 756GB NVMe) — Active Directory attack lab with Windows Server 2025 DC, Windows 11 domain client, Kali Linux attacker, and Metasploitable 2 target. Remote access via Tailscale, Wake on LAN via Pi 4.',
      tech: ['Proxmox', 'Windows Server', 'Active Directory', 'Kali Linux', 'Tailscale'],
      url: null,
      live: false,
      featured: true,
    },
    {
      id: 'wireshark-dog',
      title: 'Robotic Dog Traffic Analysis',
      category: 'academic',
      description: 'Dissected packet captures from a robotic dog in Wireshark — mapped devices, IP/MAC addresses, and traffic patterns, extracted HTTP streams, and documented security concerns in its communications.',
      tech: ['Wireshark', 'PCAP', 'Network Analysis'],
      url: null,
      live: false,
      featured: true,
    },
    {
      id: 'coyote-karate',
      title: 'Coyote Karate Academy',
      category: 'web',
      description: 'Website for CSUSB\'s Coyote Karate Academy — schedules, info, and the dojo\'s online presence. Built as CKA VP.',
      tech: ['Web Dev', 'HTML', 'CSS'],
      url: 'https://coyotekarateacademy.com/',
      live: true,
      featured: true,
    },
    {
      id: 'fresca-uncion',
      title: 'Iglesia Fresca Unción',
      category: 'web',
      description: 'Church website I built and maintain — sound and web when something needs fixing at Fresca Unción.',
      tech: ['Web Dev', 'HTML', 'CSS'],
      url: 'https://igleciafrescauncion.com/',
      live: true,
      featured: false,
    },
    {
      id: 'retro-games',
      title: 'Retro Games Arcade',
      category: 'web',
      description: 'Browser-based retro game collection on GitHub Pages — a side project showing front-end and deployment skills.',
      tech: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
      url: 'https://ronparada.github.io/retro-games/',
      live: true,
      featured: false,
    },
    {
      id: 'student-web',
      title: 'Product Website (Team Project)',
      category: 'academic',
      description: 'Collaborative product website built from raw code at San Bernardino Valley College.',
      tech: ['HTML', 'Visual Studio', 'GitHub'],
      url: null,
      live: false,
      featured: false,
    },
  ],

  labProjects: [
    {
      id: 'proxmox-lab',
      title: 'Proxmox VE Hypervisor Lab',
      icon: '🖥️',
      description: 'Type-1 hypervisor on HP EliteDesk Mini (i5-8500T, 16GB RAM, 756GB NVMe) — Active Directory attack lab with Windows Server 2025 DC, Windows 11 domain client, Kali Linux attacker, Metasploitable 2 target, and Ubuntu LXC. Wake on LAN via Pi 4. Remote access via Tailscale.',
      tags: ['Proxmox', 'Active Directory', 'Kali Linux', 'Windows Server', 'Hypervisor', 'Tailscale', 'Wake on LAN'],
    },
    {
      id: 'wazuh-siem',
      title: 'Wazuh SIEM — Mac Mini Home Lab',
      icon: '🛡️',
      description: 'Self-hosted Wazuh stack in Docker on an Apple Silicon Mac Mini — centralized SIEM for the homelab. Agents on Pi 4, file integrity monitoring, vuln scans, OpenSearch dashboard. All local hardware.',
      tags: ['Wazuh', 'SIEM', 'Docker', 'OpenSearch', 'Threat Detection', 'FIM'],
    },
    {
      id: 'home-security-lab',
      title: 'Home Security Lab',
      icon: '🏠',
      description: 'Pi-hole DNS filtering on Raspberry Pi Zero 2 W plus Ubuntu Server on Pi 4 with SSH, Tailscale VPN, and secure remote admin for self-hosted services.',
      tags: ['Raspberry Pi', 'Pi-hole', 'Tailscale', 'Ubuntu Server', 'SSH'],
    },
    {
      id: 'rf-research',
      title: 'RF & Wireless Security Research',
      icon: '📻',
      description: 'Tested Wi-Fi, Bluetooth, and sub-GHz attack surfaces in a controlled lab. Deployed Rayhunter on a mobile hotspot to detect IMSI-catcher activity.',
      tags: ['Wi-Fi', 'Bluetooth', 'Sub-GHz', 'Rayhunter', 'RF Security'],
    },
    {
      id: 'bad-beatles',
      title: '"Bad Beatles" — BadUSB Demos',
      icon: '💾',
      description: 'Custom ATMEGA32U4 USB devices for authorized red-team demos on owned hardware — shows how fast physical access leads to compromise. Demo-only; no payloads published.',
      tags: ['BadUSB', 'Red Team Demo', 'Physical Security', 'USB Policy'],
    },
    {
      id: 'live-usb-toolkit',
      title: 'Live USB Security Toolkit',
      icon: '🔧',
      description: 'Portable Kali Linux, Medicat, and diagnostic utilities for system recovery, troubleshooting, and field response scenarios.',
      tags: ['Kali Linux', 'Medicat', 'Incident Response'],
    },
    {
      id: 'meshtastic',
      title: 'Meshtastic Network + Discord Bridge',
      github: 'https://github.com/ronparada/meshtastic-discord-bridge',
      icon: '📡',
      sideProject: true,
      description: 'Python Discord bot bridging a 3-node LoRa mesh to Discord in real time — systemd service on Pi 4, 5-channel routing, auto-reconnect.',
      tags: ['Meshtastic', 'LoRa', 'Python', 'Discord.py', 'systemd'],
    },
    {
      id: 'ai-automation',
      title: 'Self-Hosted AI Automation Server',
      icon: '🤖',
      sideProject: true,
      description: 'Local AI agent stack with Telegram and Discord bot integrations — private automation under my control.',
      tags: ['AI Agents', 'Telegram', 'Discord', 'Self-Hosted'],
    },
    {
      id: 'media-server',
      title: 'Self-Hosted Media Server',
      icon: '🎬',
      sideProject: true,
      description: 'Plex and Jellyfin on Raspberry Pi 4 with external storage — accessible via Tailscale.',
      tags: ['Plex', 'Jellyfin', 'Raspberry Pi', 'Tailscale'],
    },
    {
      id: 'defcon-badge',
      title: 'DEF CON 32 Badge — Firmware',
      icon: '🎮',
      sideProject: true,
      description: 'Fixed SD filesystem issues on an RP2350 DEF CON 32 badge, flashed custom firmware, and loaded homebrew ROMs — embedded troubleshooting project.',
      tags: ['RP2350', 'Embedded Firmware', 'FAT32', 'Bootloader'],
    },
  ],

  skills: [
    'Incident Response', 'Network Security', 'SIEM / Wazuh', 'Wireshark',
    'Penetration Testing', 'Active Directory', 'Linux', 'Python',
    'Firewall Hardening', 'Threat Analysis', 'NIST 800-53', 'Docker',
    'Web Development', 'Troubleshooting', 'Spanish (Fluent)',
  ],

  certifications: {
    professional: [
      { name: 'CompTIA Security+ ce', detail: 'Expires Jul 2028' },
      { name: 'Certified in Cybersecurity (CC)', detail: 'ISC² · Expires Jan 2027' },
    ],
    labs: [
      { name: 'TestOut Linux Pro', detail: 'TestOut · Aug 2025' },
      { name: 'TestOut Routing and Switching Pro', detail: 'TestOut · Aug 2025' },
    ],
  },

  education: [
    {
      degree: 'MS, Information Systems & Technology — Cybersecurity',
      school: 'California State University, San Bernardino',
      period: '05/2024 – 05/2026',
      note: 'GPA 4.00 · Graduated May 16, 2026',
    },
    {
      degree: 'BS, Information Systems & Technology — Cybersecurity',
      school: 'California State University, San Bernardino',
      period: '01/2022 – 05/2024',
      note: 'GPA 3.95 · Summa Cum Laude · Dean\'s List',
    },
    {
      degree: 'AS, Computer Science',
      school: 'San Bernardino Valley College',
      period: '01/2020 – 05/2022',
      note: 'GPA 3.88 · Dean\'s List',
    },
  ],

  bootSequence: [
    '[ OK ] Initializing portfolio kernel...',
    '[ OK ] Loading cybersecurity modules...',
    '[ OK ] Mounting /projects',
    '[ OK ] Homelab services: online (private)',
    '[ OK ] Graduate status: confirmed',
    '[ OK ] Terminal interface ready',
    '',
    'Welcome, visitor. Type `help` in the terminal below.',
  ],
};
